services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    restart: always
    command: "azurite-blob --blobHost 0.0.0.0 --blobPort 10000 --loose"
    ports:
      - "10000:10000"